# Generated by Django 3.2.5 on 2021-07-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], default='buyer', max_length=10, null=True),
        ),
    ]
