# Generated by Django 3.2.5 on 2021-07-28 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sellerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
