# Generated by Django 3.2.5 on 2021-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sellerrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='address',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeuser',
            name='contact_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
