# Generated by Django 3.2.5 on 2021-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210729_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
