# Generated by Django 3.2.5 on 2021-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customeuser_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
