# Generated by Django 3.2.5 on 2021-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customeuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='proof',
            field=models.FileField(default='', upload_to='proofs'),
        ),
    ]
