# Generated by Django 3.2.5 on 2021-08-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210805_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='message',
        ),
    ]
