# Generated by Django 3.2.5 on 2021-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
