# Generated by Django 3.2.5 on 2021-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customeuser_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
