# Generated by Django 3.2.5 on 2021-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customeuser_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
