# Generated by Django 3.2.5 on 2021-10-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210816_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='amountPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
    ]
