# Generated by Django 3.2.5 on 2021-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='items'),
        ),
    ]
