# Generated by Django 3.2.5 on 2021-08-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210809_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.item'),
        ),
    ]
