# Generated by Django 3.2.5 on 2021-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_item_color_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_size',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 's'), ('m', 'm'), ('l', 'l')], max_length=5, null=True),
        ),
    ]
