# Generated by Django 3.2.5 on 2021-08-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_item_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.CreateModel(
            name='item_qty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item_color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item_size')),
            ],
        ),
    ]
