# Generated by Django 3.2.5 on 2021-08-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210813_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_qty',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_qty', to='products.item_color'),
        ),
        migrations.AlterField(
            model_name='item_qty',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_qty', to='products.item_size'),
        ),
    ]
