# Generated by Django 3.2.5 on 2021-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210813_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_size',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('No_Size', 'No_Size')], max_length=20, null=True),
        ),
    ]
