# Generated by Django 3.2.5 on 2021-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_item_size_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra_Images',
            new_name='Images',
        ),
        migrations.AddField(
            model_name='item_qty',
            name='image',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='color_qty', to='products.images'),
            preserve_default=False,
        ),
    ]
