# Generated by Django 3.2.5 on 2021-08-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_qty',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_qty', to='products.images'),
        ),
    ]
