# Generated by Django 3.2.5 on 2021-08-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='color',
            field=models.ForeignKey(default=259, on_delete=django.db.models.deletion.CASCADE, related_name='color_image_qty', to='products.item_color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='size',
            field=models.ForeignKey(default=204, on_delete=django.db.models.deletion.CASCADE, related_name='size_image_qty', to='products.item_size'),
            preserve_default=False,
        ),
    ]
