# Generated by Django 3.2.5 on 2021-08-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210824_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_image_qty', to='products.item_color'),
        ),
        migrations.AlterField(
            model_name='images',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_image_qty', to='products.item_size'),
        ),
    ]
