# Generated by Django 3.2.5 on 2021-10-22 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_sellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to='users.customeuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
