# Generated by Django 3.2.5 on 2021-10-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='seller',
        ),
    ]
