# Generated by Django 3.2.5 on 2021-10-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_productreview_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poster')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
