# Generated by Django 3.2.5 on 2021-10-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
